import { and, eq, sql } from "drizzle-orm";
import { db, presetCurriculaTable } from "@workspace/db";

// Hardwired preset curriculum catalog. Content is extracted from the official
// South African CAPS documents supplied to Slate; entries are seeded into
// `slate_preset_curricula` on bootstrap and used to gate class creation.
// Adding a new subject = add an entry here (and optionally a document upload
// via the admin path later).

type PresetEntry = {
  phase: string;
  subject: string;
  gradeMin: number;
  gradeMax: number;
  sourceName: string;
  sequence: string[];
  // Per-module assessment guidelines fed into Gemini marking for classes on
  // this preset. Uploaded one document at a time; empty until supplied.
  assessmentGuide: string;
};

// Stadio is a special grade beyond the school band (Grade 4-12); it is stored
// internally as grade 13 and labelled "Stadio" everywhere. Its "subjects" are
// modules, not CAPS subjects.
export const STADIO_GRADE = 13;

// Grade R (reception year) is the grade below Grade 1; it is stored as 0.
export const GRADE_R = 0;

export function gradeName(grade: number): string {
  if (grade === STADIO_GRADE) return "Stadio";
  if (grade === GRADE_R) return "Grade R";
  return `Grade ${grade}`;
}

const CAPS_IP_SS = "CAPS Social Sciences Grades 4-6 (Intermediate Phase)";

export const PRESET_CURRICULA: PresetEntry[] = [
  // ---- FOUNDATION PHASE (Grade R-3) ----
  {
    phase: "FOUNDATION_PHASE",
    subject: "Mathematics",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS Mathematics Grade R and Grades 1-3 (Foundation Phase)",
    // The grade overviews are topic rows against four term columns, so these entries carry the grade only.
    sequence: [
      "Grade R · Count objects 1 to 5; count forwards/backwards in ones; recognize symbol and name for number 1",
      "Grade R · Spatial relationships: position of objects (in front, behind, on, under); build 6-piece puzzles",
      "Grade R · Time: sequence daily events; identify day/night; introduce weather chart and days of the week",
      "Grade R · Count objects 1 to 7; recognize symbols/names 2 to 4; compare collections (more, less, equal to)",
      "Grade R · Geometric patterns: copy, complete, and create repeating patterns using physical objects",
      "Grade R · 3-D objects and 2-D shapes: sort by size, primary colours, and shape (circle, triangle, square)",
      "Grade R · Length and Mass: compare long/short, tall/taller; compare mass concretely (light and heavy)",
      "Grade R · Count objects 1 to 10; recognize symbols/names 5 to 7; solve oral addition/subtraction up to 7",
      "Grade R · 2-D shapes: recognize rectangle; shape conservation; build 18-piece puzzles; identify symmetry in self",
      "Grade R · Money: identify South African coins (20c to R5); Capacity: compare empty, full, a lot, a little",
      "Grade R · Count objects 0 to 10; count in twos; recognize symbols/names 0 to 10; oral word problems up to 10",
      "Grade R · Money: recognize South African bank notes (R10, R20, R50, R100, R200)",
      "Grade R · Directionality: move self forwards, backwards, up, down, left, right; build 24-piece puzzles",
      "Grade R · Data Handling: collect, sort, and represent objects on a pictograph; read and interpret graphs",
      "Grade 1 · Term 1 · Count objects to 10; count forwards and backwards in ones between 1 and 20",
      "Grade 1 · Term 1 · Read number symbols 1 to 20; write symbols and names 1 to 5",
      "Grade 1 · Term 1 · Compare and order objects and numbers up to 5; solve addition and subtraction to 5",
      "Grade 1 · Term 1 · Identify 3-D ball and box shapes; use language of position to describe object relations",
      "Grade 1 · Term 2 · Count objects to 20; count in 1s, 2s, 5s, and 10s up to 50",
      "Grade 1 · Term 2 · Read symbols 1 to 50; write symbols and names 1 to 10",
      "Grade 1 · Term 2 · Solve addition, subtraction, and repeated addition word problems with answers up to 10",
      "Grade 1 · Term 2 · Identify South African coins up to R5; solve money problems up to R10",
      "Grade 1 · Term 2 · Describe and sort 2-D shapes (circles, triangles, squares) by size, colour, and sides",
      "Grade 1 · Term 3 · Count objects to 40; count in 1s, 2s, 5s, and 10s up to 80",
      "Grade 1 · Term 3 · Decompose numbers 11 to 15 into tens and ones; practice number bonds to 9",
      "Grade 1 · Term 3 · Solve addition, subtraction, and grouping word problems with answers up to 15",
      "Grade 1 · Term 3 · Investigate 3-D objects that roll or slide; draw lines of symmetry in 2-D shapes",
      "Grade 1 · Term 3 · Measure mass and capacity using balancing scales and non-standard measures",
      "Grade 1 · Term 4 · Count objects to 50; count in 1s, 2s, 5s, and 10s up to 100",
      "Grade 1 · Term 4 · Order numbers to 20; use ordinal numbers first to tenth to show position",
      "Grade 1 · Term 4 · Solve addition, subtraction, and sharing word problems with answers up to 20",
      "Grade 1 · Term 4 · Identify patterns in nature; match different views of everyday 3-D objects",
      "Grade 2 · Count objects reliably up to 200, and count forwards and backwards in 1s, 2s, 3s, 4s, 5s, 10s",
      "Grade 2 · Read and write number symbols up to 200 and number names up to 100",
      "Grade 2 · Compare and order numbers up to 99, and use ordinal numbers up to twentieth",
      "Grade 2 · Decompose two-digit numbers into multiples of tens and units up to 99",
      "Grade 2 · Solve addition and subtraction word problems in context with answers up to 99",
      "Grade 2 · Solve word problems involving repeated addition leading to multiplication up to 50",
      "Grade 2 · Solve grouping and sharing word problems up to 50, including remainders",
      "Grade 2 · Solve money problems involving totals and change in cents up to 90c and rands to R99",
      "Grade 2 · Context-free addition and subtraction up to 99, and number bonds to 20",
      "Grade 2 · Multiply numbers 1 to 10 by 2, 3, 4, and 5 using appropriate symbols",
      "Grade 2 · Use and name fractions including halves, quarters, thirds, and fifths in diagrammatic form",
      "Grade 2 · Copy, extend, create and describe geometric patterns and number patterns up to 200",
      "Grade 2 · Describe position and views of objects, and follow directions to move around",
      "Grade 2 · Describe, sort and compare 3-D objects including spheres, prisms, and cylinders",
      "Grade 2 · Describe, sort and compare 2-D shapes and draw lines of symmetry",
      "Grade 2 · Tell 12-hour time in hours, half hours, and quarter hours on analogue clocks",
      "Grade 2 · Estimate, measure, compare and record length, mass, and capacity using standard units",
      "Grade 2 · Collect, organise, represent and analyse data in a pictograph with 1-to-1 correspondence",
      "Grade 3 · Count objects up to 1000; count forwards and backwards in 1s, 2s, 3s, 4s, 5s, 10s, 50s, 100s",
      "Grade 3 · Read and write number symbols and names to 1000; compare and order numbers to 999",
      "Grade 3 · Decompose 3-digit numbers up to 999 into hundreds, tens, and units to show place value",
      "Grade 3 · Solve addition and subtraction problems up to 999; practice number bonds to 30",
      "Grade 3 · Solve multiplication and division problems up to 100; multiply and divide by 2, 3, 4, 5, 10",
      "Grade 3 · Solve sharing problems leading to unitary and non-unitary fractions like halves, thirds, quarters",
      "Grade 3 · Solve money problems involving totals, change, and converting between rands and cents",
      "Grade 3 · Copy, extend, and create geometric patterns using physical objects and drawings",
      "Grade 3 · Copy, extend, and describe number sequences up to 1000 counting forwards and backwards",
      "Grade 3 · Match views of objects; follow and give directions; read and draw informal maps",
      "Grade 3 · Recognise, name, and build 3-D objects (spheres, prisms, cylinders, pyramids, cones)",
      "Grade 3 · Describe and draw 2-D shapes (circles, triangles, squares, rectangles); identify symmetry",
      "Grade 3 · Tell 12-hour time on analogue and digital clocks; read calendars and calculate length of time",
      "Grade 3 · Measure length (m, cm), mass (kg, g), and capacity (l, ml) using informal and formal tools",
      "Grade 3 · Investigate perimeter of 2-D shapes and area using tiling",
      "Grade 3 · Collect, organise, and represent data in tables, bar graphs, and pictographs; interpret data",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "English Home Language",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS English Home Language Grades R-3 (Foundation Phase)",
    sequence: [
      "Grade R · Term 1 · Oral Language: recites simple rhymes and identifies body parts",
      "Grade R · Term 1 · Emergent Reading: recognises own name and tracks print from left to right",
      "Grade R · Term 1 · Emergent Writing: develops fine-motor control, traces outlines, and copies own name",
      "Grade R · Term 2 · Oral Language: follows multi-part instructions and classifies objects by shape or size",
      "Grade R · Term 2 · Emergent Reading: reads calendar words, identifies rhyming words, and claps syllables",
      "Grade R · Term 2 · Emergent Writing: traces patterns, copies letters, and uses correct pencil grip",
      "Grade R · Term 3 · Oral Language: listens to complex instructions and completes 10 to 20 piece puzzles",
      "Grade R · Term 3 · Emergent Reading: reads predictable sentences and recognises initial consonant sounds",
      "Grade R · Term 3 · Emergent Writing: draws personal experiences, adding a word, and groups rhyming pictures",
      "Grade R · Term 4 · Oral Language: passes on messages and copies 2-D patterns using 3-D shapes",
      "Grade R · Term 4 · Emergent Reading: matches words to pictures and reads classroom high-frequency words",
      "Grade R · Term 4 · Emergent Writing: forms lower case letters correctly and copies short sentences",
      "Grade 1 · Term 1 · Listening and responding to instructions, stories, rhymes, poems and songs",
      "Grade 1 · Term 1 · Talking about personal experiences and describing objects",
      "Grade 1 · Term 1 · Phonemic awareness and letter-sound relationships of single letters",
      "Grade 1 · Term 1 · Emergent reading skills: book handling, picture interpretation, environmental print",
      "Grade 1 · Term 1 · Handwriting: fine motor skills, letter formation (lowercase), copying words and sentences",
      "Grade 1 · Term 1 · Shared, group, and independent writing: drawing to convey messages, writing captions and simple words",
      "Grade 1 · Term 2 · Listening and speaking: passing messages, identifying main ideas in stories, asking questions",
      "Grade 1 · Term 2 · Phonics: identifying letter-sound relationships of most single letters, building word families",
      "Grade 1 · Term 2 · Reading strategies: using context clues, structural analysis, and self-monitoring",
      "Grade 1 · Term 2 · Handwriting: forming lowercase and frequently used capital letters, correct spacing",
      "Grade 1 · Term 2 · Writing: drawing with captions, writing own news, building word banks and personal dictionaries",
      "Grade 1 · Term 3 · Listening and speaking: role-playing, identifying similarities and differences, expanding vocabulary",
      "Grade 1 · Term 3 · Phonics: consonant blends and digraphs (sh, ch, th), building 3-letter words",
      "Grade 1 · Term 3 · Reading comprehension: identifying sequence, setting, cause and effect, giving opinions",
      "Grade 1 · Term 3 · Writing process: drafting, editing, publishing, using capital letters and full stops",
      "Grade 1 · Term 4 · Listening and speaking: expressing feelings, using language imaginatively, classifying information",
      "Grade 1 · Term 4 · Phonics: revising digraphs, new consonant blends, plurals ('s', 'es'), spelling words",
      "Grade 1 · Term 4 · Reading: identifying initial problem in a story, understanding punctuation, reading own writing",
      "Grade 1 · Term 4 · Writing: using present and past tense, plurals, prepositions, organizing information graphically",
      "Grade 2 · Term 1 · Phonics: single letters, digraphs (sh, ch, th, wh), blends, and vowel digraphs (oo, ee)",
      "Grade 2 · Term 1 · Reading: shared and guided reading, predicting stories, and sequencing events",
      "Grade 2 · Term 1 · Handwriting: correct formation of 26 lower and upper case letters and spacing",
      "Grade 2 · Term 1 · Writing: writes three sentences of personal news or creative story with punctuation",
      "Grade 2 · Term 2 · Phonics: 3-letter consonant blends, new vowel digraphs (oa, ea, oo, ai), and silent 'e'",
      "Grade 2 · Term 2 · Reading: cause-effect relations, characters, setting, and interpreting advertisements",
      "Grade 2 · Term 2 · Handwriting: print script on 17mm lines, copies a paragraph, and joined script patterns",
      "Grade 2 · Term 2 · Writing: writes a thank you card and a five-sentence story using a writing frame",
      "Grade 2 · Term 3 · Phonics: plurals (s, es), suffixes (ing, ed), double consonants, and diphthongs (oy, oi)",
      "Grade 2 · Term 3 · Reading: sequence and setting, synonyms and antonyms, and interpreting calendars",
      "Grade 2 · Term 3 · Handwriting: transition to joined script, copying patterns and short words",
      "Grade 2 · Term 3 · Writing: drafts a six-sentence story and writes 1-2 paragraphs on personal experiences",
      "Grade 2 · Term 4 · Phonics: five new vowel digraphs (ar, er, ir, or, ur), suffixes (-ly, -ies), and dictation",
      "Grade 2 · Term 4 · Reading: fiction and non-fiction, apostrophes (possession/contraction), and self-correction",
      "Grade 2 · Term 4 · Handwriting: completes joined script letters, short sentences, and capital letters",
      "Grade 2 · Term 4 · Writing: writes a simple poem, a two-paragraph story, recipes, and charts",
      "Grade 3 · Term 1 · Listening and responding to instructions and stories",
      "Grade 3 · Term 1 · Phonics: letter-sound relationships, digraphs, rhyming words, spelling",
      "Grade 3 · Term 1 · Shared, Guided, and Independent Reading strategies and comprehension",
      "Grade 3 · Term 1 · Handwriting: joined script, letter formation, spacing",
      "Grade 3 · Term 1 · Writing: sentences, paragraphs, stories, grammar, punctuation",
      "Grade 3 · Term 2 · Listening and responding to announcements, stories, and discussions",
      "Grade 3 · Term 2 · Oral presentations and telling stories with plot and characters",
      "Grade 3 · Term 2 · Phonics: vowel blends, digraphs, homophones, word building",
      "Grade 3 · Term 2 · Reading: non-fiction texts, information retrieval, fluency, expression",
      "Grade 3 · Term 2 · Handwriting: transition to joined script, copying, speed",
      "Grade 3 · Term 2 · Writing: paragraphs, stories, diary, book reviews, grammar, editing",
      "Grade 3 · Term 3 · Oral presentations, interviews, discussions, sequencing events",
      "Grade 3 · Term 3 · Phonics: silent letters, homonyms, homophones, spelling",
      "Grade 3 · Term 3 · Reading: different genres (plays, poems), dictionary use, comprehension",
      "Grade 3 · Term 3 · Writing: personal texts (diary, letter), story drafting and publishing",
      "Grade 3 · Term 3 · Grammar: sentence types, parts of speech, conjunctions",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "Afrikaans Huistaal (Home Language)",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS Afrikaans Huistaal Graad R-3 (Grondslagfase / Foundation Phase)",
    sequence: [
      "Graad R · Term 1 · Luister en praat: eenvoudige vrae en instruksies (Listening and speaking: simple questions and instructions)",
      "Graad R · Term 1 · Luister en praat: stories, liedjies en rympies (Listening and speaking: stories, songs and rhymes)",
      "Graad R · Term 1 · Luister en praat: begrippe en redenering (Listening and speaking: concepts and reasoning)",
      "Graad R · Term 1 · Ontluikende lees: boekhantering en prentinterpretasie (Emergent reading: book handling and picture interpretation)",
      "Graad R · Term 1 · Ontluikende lees: klankbewustheid en woordherkenning (Emergent reading: phonological awareness and word recognition)",
      "Graad R · Term 1 · Ontluikende skryf: fynmotoriese vaardighede en patrone (Emergent writing: fine motor skills and patterns)",
      "Graad R · Term 2 · Luister en praat: beurtname en besprekings (Listening and speaking: turn-taking and discussions)",
      "Graad R · Term 2 · Ontluikende lees: voorspel stories en dramatiseer (Emergent reading: predict stories and dramatize)",
      "Graad R · Term 2 · Ontluikende skryf: letters en syfers namaken (Emergent writing: imitating letters and numbers)",
      "Graad R · Term 3 · Luister en praat: komplekse instruksies en stories (Listening and speaking: complex instructions and stories)",
      "Graad R · Term 3 · Ontluikende lees: hoëfrekwensie woorde en storielyn (Emergent reading: high-frequency words and storyline)",
      "Graad R · Term 3 · Ontluikende skryf: letters vorm en boodskappe teken (Emergent writing: forming letters and drawing messages)",
      "Graad R · Term 4 · Luister en praat: boodskappe oordra en redeneer (Listening and speaking: conveying messages and reasoning)",
      "Graad R · Term 4 · Ontluikende lees: prent- en woordraaisels (Emergent reading: picture and word puzzles)",
      "Graad 1 · Term 1 · Luister: deel ervarings en beskryf die weer [Listening: sharing experiences and describing weather]",
      "Graad 1 · Term 1 · Klanke: letter-klank-verhouding (l, o, h, m, a, b, t) [Phonics: letter-sound relationship]",
      "Graad 1 · Term 1 · Lees: ontluikende leesvaardighede en boekkonsep [Reading: emergent reading and book concept]",
      "Graad 1 · Term 1 · Handskrif: patrone en kleinletters l, o, h, m, a, b, t [Handwriting: lowercase letters]",
      "Graad 1 · Term 2 · Klanke: 13 enkelkonsonante en woordfamilies [Phonics: 13 single consonants and word families]",
      "Graad 1 · Term 2 · Lees: hardop en stillees in begeleide leesgroepe [Reading: aloud and silent guided reading]",
      "Graad 1 · Term 2 · Handskrif: kleinletters en hoofletters A, C, H, I, T, W [Handwriting: lowercase and capitals]",
      "Graad 1 · Term 2 · Skryf: een eie nuussin en persoonlike woordeboek [Writing: news sentence and personal dictionary]",
      "Graad 1 · Term 3 · Klanke: dubbelklanke (aa, oo, ee, uu) [Phonics: double vowels (aa, oo, ee, uu)]",
      "Graad 1 · Term 3 · Lees: oorsaak en gevolg en hoër-orde-vrae [Reading: cause and effect and higher-order questions]",
      "Graad 1 · Term 3 · Handskrif: hoofletters B, D, E, F, G, L, M, N, O, P, R, S, Y [Handwriting: uppercase letters]",
      "Graad 1 · Term 3 · Skryf: boodskap in kaartjie en sinne in verlede tyd [Writing: card message and past tense]",
      "Graad 1 · Term 4 · Klanke: tweeklanke (ie, ou, eu, ei, oe, ui) en meervoude [Phonics: diphthongs and plurals]",
      "Graad 1 · Term 4 · Lees: lees met toenemende vlotheid en uitdrukking [Reading: reading with fluency and expression]",
      "Graad 1 · Term 4 · Skryf: drie sinne met spelling en voorsetsels [Writing: three sentences and prepositions]",
      "Graad 2 · Term 1 · Mondeling: vertel persoonlike nuus [Oral: telling personal news]",
      "Graad 2 · Term 1 · Klanke: hersiening van enkel- en dubbelklanke [Phonics: revision of single and double sounds]",
      "Graad 2 · Term 1 · Lees: voorspel vanaf boekomslag [Reading: predicting from book cover]",
      "Graad 2 · Term 1 · Skryf: vorming van letters en skryf eie nuus [Writing: forming letters and writing own news]",
      "Graad 2 · Term 2 · Mondeling: vergelyk en klassifiseer dinge [Oral: comparing and classifying things]",
      "Graad 2 · Term 2 · Klanke: tweeklanke (oei, eeu, aai, ooi) [Phonics: diphthongs (oei, eeu, aai, ooi)]",
      "Graad 2 · Term 2 · Lees: oorsaak en gevolg en advertensies [Reading: cause and effect and advertisements]",
      "Graad 2 · Term 2 · Skryf: skryf een paragraaf met skryfraam [Writing: writing a paragraph using a writing frame]",
      "Graad 2 · Term 3 · Mondeling: voorspel die slot van stories [Oral: predicting the ending of stories]",
      "Graad 2 · Term 3 · Klanke: drieletterkombinasies (spr, str, skr) [Phonics: three-letter blends (spr, str, skr)]",
      "Graad 2 · Term 3 · Lees: identifiseer sinonieme en antonieme [Reading: identifying synonyms and antonyms]",
      "Graad 2 · Term 3 · Skryf: oorgang na lopende skrif [Writing: transition to cursive writing]",
      "Graad 2 · Term 4 · Klanke: konsonante aan die einde van woorde [Phonics: consonant blends at word endings]",
      "Graad 2 · Term 4 · Lees: lees fiksie en niefiksie [Reading: reading fiction and non-fiction]",
      "Graad 2 · Term 4 · Skryf: skryf van resepte en tabelle [Writing: writing recipes and tables]",
      "Graad 3 · Term 1 · Luister en praat (Listening and speaking)",
      "Graad 3 · Term 1 · Klanke en woordbou (Phonics and word building)",
      "Graad 3 · Term 1 · Gedeelde, groepbegeleide en selfstandige lees (Shared, group-guided and independent reading)",
      "Graad 3 · Term 1 · Handskrif (Handwriting)",
      "Graad 3 · Term 1 · Skryf (Writing)",
      "Graad 3 · Term 2 · Luister en praat (Listening and speaking)",
      "Graad 3 · Term 2 · Klanke en leesaktiwiteite (Phonics and reading activities)",
      "Graad 3 · Term 2 · Handskrif en skryf (Handwriting and writing)",
      "Graad 3 · Term 3 · Luister en praat (Listening and speaking)",
      "Graad 3 · Term 3 · Klanke en lees (Phonics and reading)",
      "Graad 3 · Term 3 · Handskrif en skryf (Handwriting and writing)",
      "Graad 3 · Term 4 · Luister en praat (Listening and speaking)",
      "Graad 3 · Term 4 · Klanke en lees (Phonics and reading)",
      "Graad 3 · Term 4 · Handskrif en skryf (Handwriting and writing)",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "Sesotho Puo ya Lapeng (Home Language)",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS Sesotho Puo ya Lapeng Dikereite R-3 (Foundation Phase)",
    sequence: [
      "Kereite ya R · Term 1 · Ho mamela le ho bua (Listening and speaking)",
      "Kereite ya R · Term 1 · Ho sebedisa puo ho ntshetsa pele dikgopolokutlwisiso (Using language to develop conceptual understanding)",
      "Kereite ya R · Term 1 · Ho sebedisa puo ho nahana le ho fana ka mabaka (Using language to think and reason)",
      "Kereite ya R · Term 1 · Ho sebedisa puo ho etsa dipatlisiso le ho utolla (Using language to investigate and explore)",
      "Kereite ya R · Term 1 · Ho thuisa tlhahisoleseding (Processing information)",
      "Kereite ya R · Term 1 · Ho sebedisa ditemoso tse bonwang le tsa ditshwantsho ho etsa moelelo (Using visual and pictorial cues to make meaning)",
      "Kereite ya R · Term 1 · Padiso ya sethatho ya moithuti (Emergent reading)",
      "Kereite ya R · Term 1 · Ho bala ka kopanelo/Padisommoho (Shared reading)",
      "Kereite ya R · Term 1 · Temoho ya kamano ya kaho ya ditlhaku le medumo (Phonological awareness)",
      "Kereite ya R · Term 1 · Mongolo wa sethatho wa moithuti (Emergent writing)",
      "Kereite ya R · Term 2 · Ho bala ka boikemelo (Independent reading)",
      "Kereite ya R · Term 2 · Sebetsa ka mantswe (Working with words)",
      "Kereite ya R · Term 3 · Ho fetisa molaetsa (Conveying a message)",
      "Kereite ya R · Term 4 · Ho sebedisa disebediswa tsa ho ngola (Using writing tools)",
      "Kereite ya 1 · Term 1 · Mamela ditaelo le ho hlahlamanya ditshwantsho [Listen to instructions and sequence pictures]",
      "Kereite ya 1 · Term 1 · Medumo le ditlhaku (didumannotshi 5, didumammoho 3) [Phonics and letters (5 vowels, 3 consonants)]",
      "Kereite ya 1 · Term 1 · Bokgoni ba padiso ya sethatho le ho tshwara buka [Emergent reading skills and book handling]",
      "Kereite ya 1 · Term 1 · Motsamao wa mesifa e menyane le ho bopa ditlhaku [Fine motor skills and letter formation]",
      "Kereite ya 1 · Term 2 · Pheta ditaba tsa boiphihlelo le ho hlalosa dintho [Retell personal experiences and describe objects]",
      "Kereite ya 1 · Term 2 · Medumo le ditlhaku (didumannotshi 3, didumammoho 13) [Phonics and letters (3 vowels, 13 consonants)]",
      "Kereite ya 1 · Term 2 · Padisommoho (dintlha tsa sehlooho le baphetwa) [Shared reading (main ideas and characters)]",
      "Kereite ya 1 · Term 2 · Ngola ditlhaku tse nyane tse 20 le ditlhaku tse kgolo [Write 20 lower-case and capital letters]",
      "Kereite ya 1 · Term 3 · Tatelano ya ditshwantsho le ho araba dipotso paleng [Sequence pictures and answer story questions]",
      "Kereite ya 1 · Term 3 · Didumammoho tse kopaneng (ntja, mpa, kgomo, tjhesa) [Consonant blends (ntja, mpa, kgomo, tjhesa)]",
      "Kereite ya 1 · Term 3 · Padisommoho (sesosa le ditlamorao, dipotso tsa monahano) [Shared reading (cause, effect, thinking questions)]",
      "Kereite ya 1 · Term 3 · Bopa ditlhaku tse kgolo, dipalo le ho ngola dipolelo [Form capital letters, numbers and write sentences]",
      "Kereite ya 1 · Term 4 · Pheta pale e tsebahalang e nang le qalo, mmele le qetelo [Retell a familiar story with beginning, middle, end]",
      "Kereite ya 1 · Term 4 · Motswako wa didumammoho (tsela, thola, -n-tlh-a) [Consonant blends (tsela, thola, -n-tlh-a)]",
      "Kereite ya 1 · Term 4 · Ho bala ka tataiso (bothata ba pale le matshwao a puo) [Guided reading (story problem and punctuation)]",
      "Kereite ya 1 · Term 4 · Ngola dipolelo tse tharo le thutapuo ha a ngola [Write three sentences and grammar in writing]",
      "Kereite ya 2 · Term 1 · Medumo ya didumammoho (ntlo, ntja, mpho) [Consonant trigraphs and blends]",
      "Kereite ya 2 · Term 1 · Pheta tlhahlamano ya diketsahalo paleng [Retell sequence of events in a story]",
      "Kereite ya 2 · Term 1 · Bopa ditlhaku tse nyane le tse kgolo tse 26 [Form 26 lowercase and uppercase letters]",
      "Kereite ya 2 · Term 1 · Ngola dipolelo tse tharo ka ditaba tsa hae [Write three sentences of personal news]",
      "Kereite ya 2 · Term 2 · Bapisa le ho hlophisa dintho (diphoofolo) [Compare and classify things (animals)]",
      "Kereite ya 2 · Term 2 · Medumo e qapodiswang ka ho tshwana empa moelelo o fapane [Homophones and homonyms]",
      "Kereite ya 2 · Term 2 · Kopitsa serapa se le seng sa mela e 3-4 [Copy a single paragraph of 3-4 lines]",
      "Kereite ya 2 · Term 2 · Ngola tema e hlahisang maikutlo jwalo ka karete ya teboho [Write a thank-you card]",
      "Kereite ya 2 · Term 3 · Mamela dipale a akanye qetello [Listen to stories and predict the ending]",
      "Kereite ya 2 · Term 3 · Medumo e tshwaetsanang mantsweng (nkgo, nka) [Nasalized consonant sounds]",
      "Kereite ya 2 · Term 3 · Ditlhaku ka mongolo o kopaneng [Copy letters in cursive/joined writing]",
      "Kereite ya 2 · Term 3 · Ngola dirapa tse 1-2 ka boiphihlelo [Write 1-2 paragraphs of personal experience]",
      "Kereite ya 2 · Term 4 · Elellwa dihlongwanthao le dikgutsufatso [Identify prefixes and abbreviations]",
      "Kereite ya 2 · Term 4 · Kopitsa ditlhaku tse kgolo ka mongolo o kopaneng [Copy capital letters in cursive]",
      "Kereite ya 2 · Term 4 · Ngola dirapa tse pedi ka boiphihlelo [Write two paragraphs of personal experience]",
      "Kereite ya 2 · Term 4 · Sebedisa sebopeho sa ho ngola resepe [Use informational format to write a recipe]",
      "Kereite ya 3 · Term 1 · Ho mamela le ho bua: Boiphihlelo ba hae le ditaelo [Listening and Speaking: Personal experience and instructions]",
      "Kereite ya 3 · Term 1 · Ho mamela le ho bua: Mookotaba le dintlha dipaleng [Listening and Speaking: Main ideas and details in stories]",
      "Kereite ya 3 · Term 1 · Ho bala le medumo: Medumo ya didumammoho le didumannotshi [Reading and Phonics: Consonant and vowel sounds]",
      "Kereite ya 3 · Term 1 · Ho bala le medumo: Ho bala ka tataiso le ka kopanelo [Reading and Phonics: Guided and shared reading]",
      "Kereite ya 3 · Term 1 · Ho ngola: Mongolo o kopaneng le ditema [Writing: Cursive writing and short texts]",
      "Kereite ya 3 · Term 2 · Ho mamela le ho bua: Ditaelo, dipale le dipuisano [Listening and Speaking: Instructions, stories and conversations]",
      "Kereite ya 3 · Term 2 · Ho bala le medumo: Metswako ya didumannotshi le mantswe [Reading and Phonics: Vowel combinations and words]",
      "Kereite ya 3 · Term 2 · Ho bala le medumo: Ho bala ka kopanelo le ka boikemelo [Reading and Phonics: Shared and independent reading]",
      "Kereite ya 3 · Term 2 · Ho ngola: Kopollo ya mantswe le dirapa [Writing: Copying words and paragraphs]",
      "Kereite ya 3 · Term 3 · Ho mamela le ho bua: Nehelano le dipotso [Listening and Speaking: Presentations and questions]",
      "Kereite ya 3 · Term 3 · Ho bala le medumo: Mopeleto le mefuta ya dithothokiso [Reading and Phonics: Spelling and poetry types]",
      "Kereite ya 3 · Term 3 · Ho ngola: Ditema le dipale tsa boiqapelo [Writing: Texts and creative stories]",
      "Kereite ya 3 · Term 4 · Ho mamela le ho bua: Puisano ya phedisano le metlae [Listening and Speaking: Social interaction and jokes]",
      "Kereite ya 3 · Term 4 · Ho bala le medumo: Medumo e rarahaneng le dikoranta [Reading and Phonics: Complex sounds and newspapers]",
      "Kereite ya 3 · Term 4 · Ho ngola: Mongolo o potlakileng le atikele ya koranta [Writing: Fast handwriting and newspaper article]",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "Life Skills",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS Life Skills Grades R-3 (Foundation Phase)",
    // The document lists Life Skills as a topic per grade with teaching hours;
    // these are those topics in document order.
    sequence: [
      "Grade R · Me",
      "Grade R · At school",
      "Grade R · In the classroom",
      "Grade R · Books",
      "Grade R · Days of the week",
      "Grade R · My body",
      "Grade R · Healthy living",
      "Grade R · Summer",
      "Grade R · Shapes and colours around us",
      "Grade R · Home",
      "Grade R · Safety",
      "Grade R · My family",
      "Grade R · Weather",
      "Grade R · Autumn",
      "Grade R · Sound",
      "Grade R · Sight",
      "Grade R · Touch",
      "Grade R · Taste and smell",
      "Grade R · Winter",
      "Grade R · Transport",
      "Grade R · Jobs people do",
      "Grade R · Water",
      "Grade R · Fruit",
      "Grade R · Vegetables",
      "Grade R · Dairy farming",
      "Grade R · Wool farming",
      "Grade R · Healthy environment",
      "Grade R · Spring",
      "Grade R · Birds",
      "Grade R · Reptiles",
      "Grade R · Dinosaurs",
      "Grade R · Wild animals",
      "Grade R · Finding out about one wild animal",
      "Grade R · Sport",
      "Grade 1 · Me",
      "Grade 1 · At school",
      "Grade 1 · Healthy habits",
      "Grade 1 · The weather",
      "Grade 1 · My family",
      "Grade 1 · Safety in the home",
      "Grade 1 · My body",
      "Grade 1 · Keeping my body safe",
      "Grade 1 · My community",
      "Grade 1 · Pets",
      "Grade 1 · Manners and responsibilities",
      "Grade 1 · Plants and seeds",
      "Grade 1 · Food",
      "Grade 1 · Homes",
      "Grade 1 · Picture maps",
      "Grade 1 · Water",
      "Grade 1 · The sky at night",
      "Grade 2 · What we need to live",
      "Grade 2 · Everyone is special",
      "Grade 2 · Healthy living",
      "Grade 2 · Seasons",
      "Grade 2 · Animals",
      "Grade 2 · Animals and creatures that live in water",
      "Grade 2 · Animal homes",
      "Grade 2 · Soil",
      "Grade 2 · Transport",
      "Grade 2 · Road safety",
      "Grade 2 · People who help us",
      "Grade 2 · Our country",
      "Grade 2 · Ways we communicate",
      "Grade 2 · Life at night",
      "Grade 3 · About me",
      "Grade 3 · Feelings",
      "Grade 3 · Health protection",
      "Grade 3 · Keeping my body safe",
      "Grade 3 · Rights and responsibilities",
      "Grade 3 · Healthy eating",
      "Grade 3 · Insects",
      "Grade 3 · Life cycles",
      "Grade 3 · Recycling",
      "Grade 3 · Public Safety",
      "Grade 3 · Pollution",
      "Grade 3 · How people lived long ago",
      "Grade 3 · Space",
      "Grade 3 · Products and processes",
      "Grade 3 · Disasters and what we should do",
      "Grade 3 · Animals and creatures that help us",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "IsiXhosa Ulwimi lwaseKhaya (Home Language)",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS IsiXhosa Home Language Grades R-3 (Foundation Phase)",
    sequence: [
      "IBanga R · Term 1 · Ukuphulaphula ngenyameko imibuzo elula nezibhengezo (Listening carefully to simple questions and announcements)",
      "IBanga R · Term 1 · Ukucula amaculo alula nokwenza izicengcelezo (Singing simple songs and doing rhymes)",
      "IBanga R · Term 1 · Ukuchonga nokuqaphela esona sandi (Identifying and recognizing the main sound)",
      "IBanga R · Term 1 · Ukufunda oonobumba aba-8 (l, m, b, s, d, c, t, o) (Learning at least 8 letters: l, m, b, s, d, c, t, o)",
      "IBanga R · Term 1 · Ukuphuhlisa ukusetyenziswa kweminwe nezandla (Developing fine motor and hand skills)",
      "IBanga R · Term 2 · Ukuphulaphula imiyalelo emibini ukuya kwemithathu (Listening to two to three instructions)",
      "IBanga R · Term 2 · Ukufunda oonobumba abali-10 (n, h, i, v, w, a) (Learning at least 10 letters: n, h, i, v, w, a)",
      "IBanga R · Term 2 · Ukwahlula izandi zamagama ngokuqhwaba (Segmenting word sounds by clapping)",
      "IBanga R · Term 3 · Ukuphulaphula imiyalelo embaxa aze asebenze ngayo (Listening to complex instructions and acting on them)",
      "IBanga R · Term 3 · Ukufunda oonobumba abali-10 (e, p, x, u, r, k) (Learning at least 10 letters: e, p, x, u, r, k)",
      "IBanga R · Term 4 · Ukuphulaphula amabali amade nokuwalandela (Listening to long stories and following them)",
      "IBanga R · Term 4 · Ukuhlaziywa koonobumba bonke be-Alfabheti abangama-26 (Revision of all 26 alphabet letters)",
      "IBanga 1 · Term 1 · Ukuphulaphula imiyalelo emifutshane nokuphendula ngokufanelekileyo (Listening to short instructions and responding appropriately)",
      "IBanga 1 · Term 1 · Ukuqonda izikhamiso aze aqale ukwakha amagama amafutshane (Understanding vowels and starting to build short words)",
      "IBanga 1 · Term 1 · Ukubamba incwadi nokuyityhila ngendlela efanelekileyo (Holding a book and turning pages correctly)",
      "IBanga 1 · Term 1 · Ukuzoba ngekhrayoni nokubumba ngumdongwe (Drawing with wax crayons and modelling with clay)",
      "IBanga 1 · Term 1 · Ukwakha oonobumba abancinane ngendlela eyiyo umz. l, o, h, m (Formation of lower-case letters correctly e.g. l, o, h, m)",
      "IBanga 1 · Term 2 · Ukuthetha ngamava akhe nokubalisa iindaba ngokulandelelana kweziganeko (Speaking about personal experiences and telling stories in sequence)",
      "IBanga 1 · Term 2 · Ukwakha amagama kusetyenziswa izandi ezinokubaqabane abathathu oonontathu (Building words using consonant blends with three letters)",
      "IBanga 1 · Term 2 · Ukufunda ngokuvakalayo efunda incwadi yakhe eqeleni ngoncedo lukatitshala (Reading aloud from their group book with teacher support)",
      "IBanga 1 · Term 2 · Ukubhala oonobumba abancinane babe ngama-20 ubuncinane ngendlela eyiyo (Writing at least 20 lower-case letters correctly)",
      "IBanga 1 · Term 3 · Ukubeka imifanekiso yebali ngokulandelelana kwayo etshatisa imifanekiso nezihloko (Ordering story pictures and matching pictures to headings)",
      "IBanga 1 · Term 3 · Ukwakha izivakalisi ezilula kusetyenziswa izandi ezifundiweyo (Building simple sentences using learned sounds)",
      "IBanga 1 · Term 3 · Ukubhala oonobumba abakhulu abasetyenziswa rhoqo ngokufanelekileyo (Writing frequently used capital letters correctly)",
      "IBanga 1 · Term 4 · Ukuphulaphula alandele imiyalelo nezaziso nezibhengezo aze aphendule (Listening and following instructions, notices and announcements)",
      "IBanga 1 · Term 4 · Ukuqala ukufundiswa kwamaqabane adibeneyo nokwakhiwa kwamagama (Beginning the teaching of consonant digraphs and word building)",
      "IBanga 1 · Term 4 · Ukubhala izivakalisi ezithathu ubuncinane ngamabali akhe (Writing at least three sentences about their own stories)",
      "IBanga 2 · Term 1 · Ukuphulaphula nokuthetha ngamava akhe [Listening and speaking about personal experiences]",
      "IBanga 2 · Term 1 · Ukubalisa ibali elinesiqalo, isiqu nesiphelo [Narrating a story with a beginning, middle and end]",
      "IBanga 2 · Term 1 · Ukwakhiwa nokubhalwa kwezivakalisi ezilula ngezandi ezingoonombini, oonontathu noonone [Building and writing simple sentences with digraphs, trigraphs and quadrigraphs]",
      "IBanga 2 · Term 1 · Ukutolika imifanekiso nokubhaliweyo umz. ifoto, intengiso [Interpreting pictures and print e.g. photo, advertisement]",
      "IBanga 2 · Term 1 · Ukubhala oonobumba abancinane nabakhulu abangama-26 ngokufanelekileyo [Writing the 26 lower and upper case letters correctly]",
      "IBanga 2 · Term 2 · Ukuthelekisa nokwahlulahlula izinto ngokobume bazo anike nenkcazo [Comparing and classifying objects by shape and giving descriptions]",
      "IBanga 2 · Term 2 · Ukufunda incwadi beyiklasi notitshala kuze kuxoxwe ngembangi [Reading a book as a class with the teacher and discussing cause and effect]",
      "IBanga 2 · Term 2 · Ukubhala elakhe ibali elinomhlathi omnye izivakalisi ezihlanu ubuncinane [Writing his/her own story with one paragraph, at least five sentences]",
      "IBanga 2 · Term 3 · Ukuphulaphula amabali athelekelele isiphelo okಥವಾ azenzele esakhe isiphelo [Listening to stories, predicting the ending or making their own ending]",
      "IBanga 2 · Term 3 · Ukutolika ulwazi kwiigrafu neethebhile umz. khalenda [Interpreting information in graphs and tables e.g. calendar]",
      "IBanga 2 · Term 3 · Ukudrafta abhale aze apapashe ibali lakhe elimigca mithandathu ubuncinane [Drafting, writing and publishing his/her story of at least six lines]",
      "IBanga 2 · Term 4 · Ukuthabatha inxaxheba kwiingxoxo ecebisa ngezihloko zengxoxo [Participating in discussions, suggesting topics for discussion]",
      "IBanga 2 · Term 4 · Ukufunda amabali ayinyani nangenabo ubunyani beyiklasi notitshala [Reading factual and non-factual stories as a class with the teacher]",
      "IBanga 2 · Term 4 · Ukubhala imihlathi emibini ubuncinane izivakalisi ezili-10 ngamava akhe neziganeko [Writing at least two paragraphs, 10 sentences, about personal experiences and events]",
      "IBanga 3 · Term 1 · Ukuthetha ngamava akhe nokubalisa iindaba (Speaking about personal experiences and telling stories)",
      "IBanga 3 · Term 1 · Ukuphulaphula imiyalelo emide elandelelanayo / embaxa (Listening to long sequential or complex instructions)",
      "IBanga 3 · Term 1 · Ukuchonga oonobumba nezandi nokwakha amagama (Identifying letters and sounds and building words)",
      "IBanga 3 · Term 1 · Ukufunda incwadi notitshala beyiklasi, kuchongwe undoqo (Reading a book with the teacher as a class, identifying the main idea)",
      "IBanga 3 · Term 1 · Ukubhala oonobumba abancinci nabakhulu ngokucacileyo (Writing lower and upper case letters clearly)",
      "IBanga 3 · Term 1 · Ukubhala umhlathi omnye okanye nangaphezulu (Writing one or more paragraphs)",
      "IBanga 3 · Term 2 · Ukuphulaphula amabali afundwa ngutitshala nakunomathotholo (Listening to stories read by the teacher and on the radio)",
      "IBanga 3 · Term 2 · Ukufunda iitekisi ezinjengezibongo, iincwadi ezinkulu, iiphowusta (Reading texts like poems, big books, posters)",
      "IBanga 3 · Term 2 · Ukubhala amagama nezivakalisi ngokusebenzisa ukubhala ngokudibanisa (Writing words and sentences using cursive/joined writing)",
      "IBanga 3 · Term 3 · Ukwenza udliwano-ndlebe nabantu ngesizathu esithile (Conducting interviews with people for a specific reason)",
      "IBanga 3 · Term 3 · Ukutolika ulwazi kwiitekisi eziyimizobo (Interpreting information in graphic texts)",
      "IBanga 3 · Term 3 · Ukudrafta, abhale, ahlele aze apapashe ibali lakhe (Drafting, writing, editing and publishing a story)",
      "IBanga 3 · Term 4 · Ukubalisa ibali esebenzisa ulwimi, izijekulo nembonakalo yobuso (Telling a story using language, gestures and facial expressions)",
      "IBanga 3 · Term 4 · Ukufunda iitekisi ezibhaliweyo beyiklasi yonke (Reading written texts with the whole class)",
      "IBanga 3 · Term 4 · Ukubhala iitekisi ezimfutshane ezikhethiweyo (Writing selected short texts)",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "IsiZulu Ulimi Lwasekhaya (Home Language)",
    gradeMin: GRADE_R,
    gradeMax: 3,
    sourceName: "CAPS IsiZulu Home Language Grades R-3 (Foundation Phase)",
    sequence: [
      "IBanga R · Term 1 · Ukulalela nokukhuluma (Listening and speaking)",
      "IBanga R · Term 1 · Amakhono okufunda kokuqala (Early reading skills)",
      "IBanga R · Term 1 · Ulwazi lwemisindo (Phonetic awareness)",
      "IBanga R · Term 1 · Ukubhala kahle ngesandla kokuqala (Early handwriting)",
      "IBanga R · Term 2 · Ukulalela nokukhuluma nezithombe (Listening, speaking and pictures)",
      "IBanga R · Term 2 · Ukufunda ngokuhlanganyela nokuzimela (Shared and independent reading)",
      "IBanga R · Term 2 · Ukusebenza ngamagama (Word work)",
      "IBanga R · Term 3 · Ukulalela imiyalelo nemibuzo (Listening to instructions and questions)",
      "IBanga R · Term 3 · Ubudlelwano bemisindo nezinhlamvu zamagama (Sound-letter relationships)",
      "IBanga R · Term 3 · Ukubhala kokuqala nokudweba (Early writing and drawing)",
      "IBanga R · Term 4 · Ukulalela nokukhuluma ngesichazimqondo (Listening and speaking for concept development)",
      "IBanga R · Term 4 · Amakhono okufunda nezincwadi ezinkulu (Reading skills and big books)",
      "IBanga R · Term 4 · Ukubhala kwezinhlamvu namagama (Writing letters and words)",
      "IBanga 1 · Term 1 · Lalela imiyalelo elula bese wenza okufanele [Listen to simple instructions and do what is required]",
      "IBanga 1 · Term 1 · Funda onkamisa nongwaqa abahlosiwe [Read targeted vowels and consonants]",
      "IBanga 1 · Term 1 · Bamba incwadi ngokuyikho uphenye kahle amakhasi [Hold a book correctly and turn pages properly]",
      "IBanga 1 · Term 1 · Dweba amaphethini ahlukahlukene nezinhlamvu [Draw various patterns and letters]",
      "IBanga 1 · Term 1 · Kopisha ubhale igama lakho, amagama amafushane nemisho [Copy and write your name, short words and sentences]",
      "IBanga 1 · Term 2 · Chaza izinto ngokweminyaka, inkomba, nangokuzilandelanisa [Describe things by age, direction, and sequence]",
      "IBanga 1 · Term 2 · Fundisa imisindo emisha c, f, g, h, j, k, p, q, t, s [Teach new sounds c, f, g, h, j, k, p, q, t, s]",
      "IBanga 1 · Term 2 · Yakha osonhlamvukazi abasetshenziswa njalo ngendlela efanele [Form frequently used capital letters correctly]",
      "IBanga 1 · Term 3 · Lalela uthole imininingwane ezindabeni ubuze imibuzo [Listen to get details in stories and ask questions]",
      "IBanga 1 · Term 3 · Funda onkamisa nongwaqa v, w, x, y, z, r, bh, sh, kh, ph [Read vowels and consonants v, w, x, y, z, r, bh, sh, kh, ph]",
      "IBanga 1 · Term 3 · Yakha izinhlamvu ezincane, osonhlamvukazi nezinombolo [Form lowercase letters, capital letters and numbers]",
      "IBanga 1 · Term 4 · Xoxa indaba enesiqalo, umzimba kanye nesiphetho [Tell a story with a beginning, middle and end]",
      "IBanga 1 · Term 4 · Yethula ongwaqa abahamba ngababili qh, ch, th, xh, hh, dl, hl, kl [Introduce consonant digraphs qh, ch, th, xh, hh, dl, hl, kl]",
      "IBanga 1 · Term 4 · Bhala imisho emithathu yakho usebenzisa imisindo oyifundile [Write three sentences of your own using sounds learned]",
      "IBanga 2 · Term 1 · Xoxa ngokwenzeka empilweni ngezindaba ezimayelana nawe (Discuss events from life, e.g., stories about yourself)",
      "IBanga 2 · Term 1 · Lalela indaba ngokuyijabulela ubuye uphendule imibuzo (Listen to a story for enjoyment and answer questions)",
      "IBanga 2 · Term 1 · Bukeza imisindo enhlamvunye nenhlamvumbili efundiwe eBangeni loku-1 (Revise single and digraph sounds learned in Grade 1)",
      "IBanga 2 · Term 1 · Funda imiyalelo elula eyenzelwe ikilasi (Read simple instructions meant for the class)",
      "IBanga 2 · Term 1 · Bhala osonhlamvukazi kanye nezinhlamvu ezincane ngendlela efanele (Write uppercase and lowercase letters correctly)",
      "IBanga 2 · Term 2 · Qhathanisa uhlele izinto uchaze ukuthi uzihlele kanjani (Compare and sort items, explaining how they are sorted)",
      "IBanga 2 · Term 2 · Funda imisindo enongwaqa abahamba ngababili njengo nw, mb, mf (Learn consonant digraph sounds like nw, mb, mf)",
      "IBanga 2 · Term 2 · Sebenzisa izinto ezibonakalayo ukuthola inhloso yesikhangisi (Use visual aids to find the purpose of an advertisement)",
      "IBanga 2 · Term 2 · Kopisha bese ubhale isigatshana esinemigqa emi-3-4 esendabeni ebhaliwe (Copy and write a 3-4 line paragraph from a written story)",
      "IBanga 2 · Term 3 · Lalela izindaba bese uqagela isiphetho kumbe uzakhele esakho isiphetho (Listen to stories and predict or create your own ending)",
      "IBanga 2 · Term 3 · Funda imisindo emisha yongwaqa abanhlamvuntathu njengo ndl, nhl (Learn new trigraph consonant sounds like ndl, nhl)",
      "IBanga 2 · Term 3 · Humusha ulwazi emathebulini alula njengekhalenda (Interpret information in simple tables like a calendar)",
      "IBanga 2 · Term 3 · Bhala 1-2 izigatshana ngezehlakalo zempilo yakho noma isigameko (Write 1-2 paragraphs about life events or an incident)",
      "IBanga 2 · Term 4 · Lalela imininingwane ezindabeni bese uphendula imibuzo esezingeni eliphezulu (Listen to details in stories and answer higher-order questions)",
      "IBanga 2 · Term 4 · Funda imisindo enongwaqa abangonhlamvuntathu njengo ncw, ndw, ngw (Learn trigraph consonant sounds like ncw, ndw, ngw)",
      "IBanga 2 · Term 4 · Bhala okungenani izigaba ezimbili ngezinto ezikwenzakalele noma imigubho yomndeni (Write at least two paragraphs about events that happened to you or family celebrations)",
      "IBanga 3 · Term 1 · Lalela imiyalelo exubile nelandelanayo (Listen to mixed and sequential instructions [at least 4] and act accordingly)",
      "IBanga 3 · Term 1 · Bukeza imisindo enhlamvunye, enhlamvumbili nenhlamvuntathu efundwe kubanga-2 (Review single, double and triple consonant sounds learned in grade 2)",
      "IBanga 3 · Term 1 · Funda imibhalo ekhulisiwe njengezinkondlo, izincwadi zokufunda ezinkulu namaphosta (Read enlarged texts like poems, big readers and posters)",
      "IBanga 3 · Term 1 · Bhala zonke izinhlamvu ezincane nezinkulu ngokubhala ngokuxhumanisa noma ngokuhlanganisa (Write all lowercase and uppercase letters using cursive or joined-up writing)",
      "IBanga 3 · Term 1 · Okungenani bhala isigaba esisodwa semisho eyi-8 (At least write one paragraph of 8 sentences such as personal stories)",
      "IBanga 3 · Term 2 · Lalela imiyalelo ejulile nelandelanayo bese wenza ngokufanele (Listen to detailed and sequential instructions [at least 5] and act accordingly)",
      "IBanga 3 · Term 2 · Yethula imisindo emisha ehlanganisa izihlamvu ezine (Introduce new sounds consisting of four letters - onhlamvune)",
      "IBanga 3 · Term 2 · Bhala okungenani izigaba ezimbili, ngezehlakalo zempilo yakho (Write at least two paragraphs [10+ sentences] about events from your life)",
      "IBanga 3 · Term 3 · Xoxa nabantu ngenhloso yokuthola kabanzi ngomsebezi womuntu awenzayo (Talk with people to find out more about someone's job)",
      "IBanga 3 · Term 3 · Funda izinhlobo ezahlukene zezinkondlo ngesihloko uxoxisane ngazo (Read different types of poetry on a topic and discuss them)",
      "IBanga 3 · Term 3 · Bhala umbhalo wakho ngezindlela ezahlukile njengo: ukubhala encwadini yakho, incwadi eya esihlobeni (Write your text in different ways such as journal writing, a letter to a relative)",
      "IBanga 3 · Term 4 · Lalela imininingwane yezindaba bese uphendula imibuzo evulekile (Listen to details of stories and answer open-ended questions)",
      "IBanga 3 · Term 4 · Abafundi bayifunde yonke lemisindo enamagama eqa onkamisa (Students learn all sounds with vowel-skipping words: mbh, mch, etc.)",
      "IBanga 3 · Term 4 · Funda umbhalo obhaliwe ikilasi lonke nothisha bese nixoxa ngabalingiswa (Read written text whole class with teacher and discuss characters, plot and life values)",
      "IBanga 3 · Term 4 · Bhala umbhalo omfushane okhethiwe owenzelwe izidingo ezehlukene njengokubala, izinkulumo mpendulwano (Write short selected texts for different needs like lists, dialogues)",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "English First Additional Language",
    gradeMin: 1,
    gradeMax: 3,
    sourceName: "CAPS English First Additional Language Grades 1-3 (Foundation Phase)",
    sequence: [
      "Grade 1 · Term 1 · Oral vocabulary about My Clothes",
      "Grade 1 · Term 1 · Stories from Big Books like The Old Man and his Hat",
      "Grade 1 · Term 1 · Initial sounds and rhyming words in stories",
      "Grade 1 · Term 1 · Shared writing of a caption for a drawing",
      "Grade 1 · Term 2 · Oral vocabulary and language structures about Food",
      "Grade 1 · Term 2 · Stories from Big Books like The Very Hungry Caterpillar",
      "Grade 1 · Term 2 · Syllable clapping and initial sounds in familiar words",
      "Grade 1 · Term 2 · Shared writing of a caption for a drawing",
      "Grade 1 · Term 3 · Oral vocabulary and adjectives about Animals",
      "Grade 1 · Term 3 · Stories from Big Books like Three Billy Goats Gruff",
      "Grade 1 · Term 3 · Syllable clapping and aural recognition of plurals",
      "Grade 1 · Term 3 · Shared writing of simple lists with headings",
      "Grade 1 · Term 4 · Oral vocabulary and the modal can about Things I can do",
      "Grade 1 · Term 4 · Stories and non-fiction texts about Animals that can fly",
      "Grade 1 · Term 4 · Rhyming words, initial sounds, and plural recognition",
      "Grade 1 · Term 4 · Shared writing of simple lists with headings",
      "Grade 2 · Term 1 · Listening to and giving a simple oral recount",
      "Grade 2 · Term 1 · Building and breaking down 3-letter words",
      "Grade 2 · Term 1 · Reading aloud in a guided reading group",
      "Grade 2 · Term 1 · Writing sentence completion by filling in missing words",
      "Grade 2 · Term 2 · Listening to stories and answering literal questions",
      "Grade 2 · Term 2 · Distinguishing aurally between long and short vowel sounds",
      "Grade 2 · Term 2 · Reading Big Books and matching sentences to pictures",
      "Grade 2 · Term 2 · Writing sentences using phonic sounds and sight words",
      "Grade 2 · Term 3 · Listening to a simple recount and answering questions",
      "Grade 2 · Term 3 · Recognizing consonant digraphs at beginning and end of words",
      "Grade 2 · Term 3 · Writing sentences using a frame",
      "Grade 2 · Term 4 · Listening to a simple recount and giving a recount using a frame",
      "Grade 2 · Term 4 · Recognizing consonant blends and vowel digraphs",
      "Grade 2 · Term 4 · Reading a short written text and answering oral questions",
      "Grade 2 · Term 4 · Writing a paragraph of at least three sentences",
      "Grade 3 · Term 1 · Wild Animals vocabulary and past tense recounts",
      "Grade 3 · Term 1 · Consonant digraphs and short 3-letter and 4-letter words",
      "Grade 3 · Term 1 · Simple present tense and possessive form of nouns",
      "Grade 3 · Term 1 · Writing paragraphs and simple instructions",
      "Grade 3 · Term 2 · Growing Things vocabulary and life cycle processes",
      "Grade 3 · Term 2 · Vowel digraphs, silent ‘e’ and consonant blends",
      "Grade 3 · Term 2 · Present progressive tense and countable and uncountable nouns",
      "Grade 3 · Term 2 · Organizing information in charts, tables or bar graphs",
      "Grade 3 · Term 3 · Making Things vocabulary and procedural instructions",
      "Grade 3 · Term 3 · Vowel digraphs and three-letter consonant blends",
      "Grade 3 · Term 3 · Past tense sentences and personal recounts",
      "Grade 3 · Term 4 · Transport vocabulary and comparative adjectives",
      "Grade 3 · Term 4 · Vowel digraphs, word families and suffixes",
      "Grade 3 · Term 4 · Future tense and comparative adjective sentences",
      "Grade 3 · Term 4 · Shared writing of a simple story",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "Afrikaans Eerste Addisionele Taal (First Additional Language)",
    gradeMin: 1,
    gradeMax: 3,
    sourceName: "CAPS Afrikaans Eerste Addisionele Taal Graad 1-3 (Grondslagfase)",
    sequence: [
      "Graad 1 · Term 1 · Mondelinge woordeskat en groetvorme (Oral vocabulary and greetings)",
      "Graad 1 · Term 1 · Meervoudsvorm van naamwoorde (Plural form of nouns)",
      "Graad 1 · Term 1 · Fiksie- en niefiksie-tekste uit Grootboeke (Fiction and non-fiction texts from Big Books)",
      "Graad 1 · Term 1 · Klankbewustheidsaktiwiteite en beginklanke (Phonological awareness and beginning sounds)",
      "Graad 1 · Term 1 · Gedeelde skryf en tekening onderskrifte (Shared writing and drawing captions)",
      "Graad 1 · Term 2 · Voedsel woordeskat en taalstrukture (Food vocabulary and language structures)",
      "Graad 1 · Term 2 · Teenwoordige tyd en negatiewe vorm (Present tense and negative form)",
      "Graad 1 · Term 2 · Lettergrepe van bekende woorde klap (Clapping syllables of familiar words)",
      "Graad 1 · Term 2 · Gedeelde lees van stories en tekste (Shared reading of stories and texts)",
      "Graad 1 · Term 3 · Diere woordeskat en byvoeglike naamwoorde (Animals vocabulary and adjectives)",
      "Graad 1 · Term 3 · Meervoude wat op s en e eindig (Plurals ending in s and e)",
      "Graad 1 · Term 3 · Eenvoudige lysie woorde met ’n opskrif (Simple list of words with a heading)",
      "Graad 1 · Term 4 · Dinge wat gedoen kan word en die woord kan (Things that can be done and the word can)",
      "Graad 1 · Term 4 · Rymende woorde en beginklanke (Rhyming words and beginning sounds)",
      "Graad 1 · Term 4 · Gedeelde skryf van ’n woordelys (Shared writing of a word list)",
      "Graad 2 · Term 1 · Mondelinge woordeskat en eenvoudige verlede tyd [Oral vocabulary and simple past tense]",
      "Graad 2 · Term 1 · Kort reekse instruksies en eenvoudige vrae [Short sequences of instructions and simple questions]",
      "Graad 2 · Term 1 · Enkelklanke en 3-letterwoorde opbou en breek [Single sounds and building and breaking 3-letter words]",
      "Graad 2 · Term 1 · Groepbegeleide lees en sigwoordeskat [Group guided lees and sight vocabulary]",
      "Graad 2 · Term 1 · Ontbrekende woorde in sinne invul [Filling in missing words in sentences]",
      "Graad 2 · Term 2 · Woordeskat oor die weer en byvoeglike naamwoorde [Weather vocabulary and adjectives]",
      "Graad 2 · Term 2 · Kort stories luister en stories dramatiseer [Listening to short stories and dramatising stories]",
      "Graad 2 · Term 2 · Kort en lang vokale en -jie/-tjie uitgange [Short and long vowels and -jie/-tjie endings]",
      "Graad 2 · Term 2 · Sinne maak met klanke en sigwoorde en leestekens [Making sentences with sounds, sight words and punctuation]",
      "Graad 2 · Term 3 · Woordeskat oor sport en rigtings (links/regs) [Sports vocabulary and directions (left/right)]",
      "Graad 2 · Term 3 · Tweeletterkombinasies aan die begin van woorde [Two-letter combinations at the beginning of words]",
      "Graad 2 · Term 3 · Sinsrame gebruik en beterskapskaartjies skryf [Using sentence frames and writing get-well cards]",
      "Graad 2 · Term 4 · Woordeskat oor seisoene en seisoenale veranderinge [Seasons vocabulary and seasonal changes]",
      "Graad 2 · Term 4 · Woordfamilies en lang vokale [Word families and long vowels]",
      "Graad 2 · Term 4 · Paragraaf van minstens drie sinne skryf [Writing a paragraph of at least three sentences]",
      "Graad 3 · Term 1 · Ontwikkel mondelinge woordeskat deur van onderwerpe en temas soos Wilde diere gebruik te maak [Develop oral vocabulary by using topics and themes such as Wild animals]",
      "Graad 3 · Term 1 · Herken tweekonsonantkombinasies aan die begin van woorde soos sk-, br-, fr-, pl- [Recognize two-consonant combinations at the beginning of words such as sk-, br-, fr-, pl-]",
      "Graad 3 · Term 1 · Skryf ’n paragraaf van 4 - 6 sinne oor ’n bekende onderwerp [Write a paragraph of 4 - 6 sentences about a familiar topic]",
      "Graad 3 · Term 1 · Verstaan en gebruik die teenwoordige tyd [Understand and use the present tense]",
      "Graad 3 · Term 2 · Ontwikkel woordeskat deur van onderwerpe en temas, soos Dinge wat groei, gebruik te maak [Develop vocabulary by using topics and themes, such as Things that grow]",
      "Graad 3 · Term 2 · Herken vokaalklanke wat uit twee letters bestaan en diftonge soos ou, ei, ui [Recognize vowel sounds consisting of two letters and diphthongs such as ou, ei, ui]",
      "Graad 3 · Term 2 · Organiseer inligting met behulp van ’n diagram, tabel of staafgrafiek soos die lewensiklus van ’n plant [Organize information using a diagram, table or bar graph such as the life cycle of a plant]",
      "Graad 3 · Term 2 · Voltooi sinne deur voorsetsels in te vul [Complete sentences by filling in prepositions]",
      "Graad 3 · Term 3 · Ontwikkel ’n mondelinge woordeskat deur van onderwerpe en temas soos Ons maak dinge gebruik te maak [Develop an oral vocabulary by using topics and themes such as We make things]",
      "Graad 3 · Term 3 · Herken driekonsonantkombinasies aan die begin van ’n woord soos strand, straat, straf [Recognize three-consonant combinations at the beginning of a word such as strand, straat, straf]",
      "Graad 3 · Term 3 · Skryf, met hulp van die onderwyser, ’n persoonlike vertelling van ervaringe [Write, with the teacher's help, a personal recount of experiences]",
      "Graad 3 · Term 3 · Verstaan en gebruik die verlede tyd [Understand and use the past tense]",
      "Graad 3 · Term 4 · Ontwikkel ’n mondelinge woordeskat deur van onderwerpe en temas soos Vervoer gebruik te maak [Develop an oral vocabulary by using topics and themes such as Transport]",
      "Graad 3 · Term 4 · Herken agtervoegsels soos -er in mooier en -ste in mooiste [Recognize suffixes such as -er in mooier and -ste in mooiste]",
      "Graad 3 · Term 4 · Organiseer inligting op ’n tabel of staafgrafiek na ’n ondersoek na vervoermiddels [Organize information on a table or bar graph after an investigation into transport]",
      "Graad 3 · Term 4 · Verstaan en gebruik byvoeglike naamwoorde in die trappe van vergelyking [Understand and use adjectives in degrees of comparison]",
    ],
    assessmentGuide: "",
  },
  {
    phase: "FOUNDATION_PHASE",
    subject: "IsiXhosa Ulwimi lokuQala oLongezelelweyo (First Additional Language)",
    gradeMin: 1,
    gradeMax: 3,
    sourceName: "CAPS IsiXhosa First Additional Language Grades 1-3 (Foundation Phase)",
    sequence: [
      "IBanga 1 · Term 1 · Iimpahla zam [My clothes]",
      "IBanga 1 · Term 1 · Ukuphulaphula amabali nokuphendula imibuzo [Listening to stories and answering questions]",
      "IBanga 1 · Term 1 · Ukunakana izandi zokuqala emagameni [Recognising initial sounds in words]",
      "IBanga 1 · Term 1 · Ukwakha nokubhala amagama nezivakalisi ezilula [Building and writing simple words and sentences]",
      "IBanga 1 · Term 2 · Ukutya [Food vocabulary and preferences]",
      "IBanga 1 · Term 2 · Ukuxoxa ngemifanekiso yezulu [Discussing weather pictures]",
      "IBanga 1 · Term 2 · Ukwahlula amalungu egama ngokuqhwaba [Clapping syllables in words]",
      "IBanga 1 · Term 2 · Ukubhala isihloko somzobo [Writing a title for a drawing]",
      "IBanga 1 · Term 3 · Izilwanyana [Animals vocabulary and descriptions]",
      "IBanga 1 · Term 3 · Ukuqaphela isininzi sezibizo [Recognising noun plurals]",
      "IBanga 1 · Term 3 · Ukwakha izivakalisi kusetyenziswa oonombini [Building sentences using consonant clusters]",
      "IBanga 1 · Term 3 · Ukubhala uluhlu lwezinto ngokwezihloko [Writing a list of things by topic]",
      "IBanga 1 · Term 4 · Izinto endinokuzenza [Things I can do]",
      "IBanga 1 · Term 4 · Ukuphulaphula ibali lesikhukukazi namantshontsho [Listening to the hen and chicks story]",
      "IBanga 1 · Term 4 · Ukwahlula amalungu amagama nezinto ezibhabhayo [Clapping syllables and flying objects]",
      "IBanga 1 · Term 4 · Ukubhala uluhlu lwezinto ezibhabhayo [Writing a list of flying things]",
      "IBanga 2 · Term 1 · Ukuphulaphula nokubalisa amabalana [Listening and telling short stories]",
      "IBanga 2 · Term 1 · Ukukhulisa isigama somlomo neeMvakalelo [Oral vocabulary development and emotions]",
      "IBanga 2 · Term 1 · Ukwakha nokucazulula amagama anoonobumba aba-3 [Building and breaking down 3-letter words]",
      "IBanga 2 · Term 1 · Ukwakha amagama ngoonontathu noonone [Building words with 3 and 4 consonant blends]",
      "IBanga 2 · Term 1 · Ukufunda kwamaQela okuKhokelwayo [Guided Group Reading]",
      "IBanga 2 · Term 1 · Ukugqibezela izivakalisi ngamagama ashiyelelweyo [Completing sentences with missing words]",
      "IBanga 2 · Term 2 · Ukuthetha ngemozulu nesigama somlomo [Talking about weather and oral vocabulary]",
      "IBanga 2 · Term 2 · Ukuphulaphula nokuphendula imibuzo ngamabali [Listening and answering questions about stories]",
      "IBanga 2 · Term 2 · Ukwakha amagama ngokuqala ngeqabane elinye [Building words starting with a single onset]",
      "IBanga 2 · Term 2 · Ubhala izivakalisi esebenzisa amagama anezandi namabonwayo [Writing sentences using phonic and sight words]",
      "IBanga 2 · Term 3 · Ukuthetha ngezemiDlalo nokulandela imiyalelo [Talking about sports and following instructions]",
      "IBanga 2 · Term 3 · Ukuqalisa oonombini bamaqabane ekuqaleni nasekupheleni [Consonant digraphs at word beginnings and endings]",
      "IBanga 2 · Term 3 · Ubhala ingcaciso yomfanekiso namasikhelo [Writing image captions and using sentence frames]",
      "IBanga 2 · Term 4 · Ukuthetha ngamaXesha onyaka nesigama sotyando [Talking about seasons and change vocabulary]",
      "IBanga 2 · Term 4 · Ukudibanisa amaqabane ohlukeneyo noonombini bezikhamiso [Consonant blends and vowel digraphs]",
      "IBanga 2 · Term 4 · Ubhala umhlathi owenziwa ngezivakalisi ezi-3 [Writing a short paragraph of at least 3 sentences]",
      "IBanga 3 · Term 1 · Izilwanyana Zasekhaya [Domestic animals]",
      "IBanga 3 · Term 1 · Ukuphulaphula nokuthetha ngamabali [Listening and speaking about stories]",
      "IBanga 3 · Term 1 · Oonobumba abancinci noonombini ekuqaleni nasekupheleni kwegama [Lowercase letters and digraphs at the beginning and end of words]",
      "IBanga 3 · Term 1 · Ukufunda nokusebenzisa izakhiwo zolwimi njengeqesha langoku [Reading and using language structures like the present tense]",
      "IBanga 3 · Term 1 · Ukubhala umhlathi ngesihloko esiqhelekileyo [Writing a paragraph on a familiar topic]",
      "IBanga 3 · Term 2 · Ukukhulisa izityalo nokulandela imiyalelo [Growing plants and following instructions]",
      "IBanga 3 · Term 2 · Ukusebenzisa izikhamiso ezingoonombini namaqabane axutyiweyo [Using vowel digraphs and consonant blends]",
      "IBanga 3 · Term 2 · Ukubhala izintlu ezinezihloko kunye netshathi okanye itheyibhile [Writing lists with headings and a chart or table]",
      "IBanga 3 · Term 2 · Ukusebenzisa imo ende yexesha langoku [Using the long form of the present tense]",
      "IBanga 3 · Term 3 · Ukwenza imaski nokulandela inkqubo [Making a mask and following a process]",
      "IBanga 3 · Term 3 · Ukufunda nokubhala amaqabane angoonontathu [Reading and writing 3-consonant clusters]",
      "IBanga 3 · Term 3 · Ukusebenzisa ixesha eladlulayo ekubhaleni [Using the past tense in writing]",
      "IBanga 3 · Term 4 · Ezothutho nokuthetha ngendlela eya esikolweni [Transport and talking about the way to school]",
      "IBanga 3 · Term 4 · Ukunakana iifamili zamagama nezimamva [Recognizing word families and suffixes]",
      "IBanga 3 · Term 4 · Ukubhala ibali elilula kunye nomhlathi [Writing a simple story and a paragraph]",
      "IBanga 3 · Term 4 · Ukusebenzisa izichazi kwizivakalisi [Using adjectives in sentences]",
    ],
    assessmentGuide: "",
  },
  {
    phase: "INTERMEDIATE_PHASE",
    subject: "Social Sciences — Geography",
    gradeMin: 4,
    gradeMax: 6,
    sourceName: CAPS_IP_SS,
    sequence: [
      "Grade 4 · Places where people live",
      "Grade 4 · Map skills",
      "Grade 4 · Food and farming in South Africa",
      "Grade 4 · Water in South Africa",
      "Grade 5 · Map skills: Africa",
      "Grade 5 · Physical features of South Africa",
      "Grade 5 · Weather, climate and vegetation of South Africa",
      "Grade 5 · Minerals and mining in South Africa",
      "Grade 6 · Map skills: World",
      "Grade 6 · Trade: South Africa and World",
      "Grade 6 · Climate and vegetation around the world",
      "Grade 6 · Population: why people live where they do",
    ],
    assessmentGuide: "",
  },
  {
    phase: "INTERMEDIATE_PHASE",
    subject: "Social Sciences — History",
    gradeMin: 4,
    gradeMax: 6,
    sourceName: CAPS_IP_SS,
    sequence: [
      "Grade 4 · Local history",
      "Grade 4 · Learning from leaders",
      "Grade 4 · Transport through time",
      "Grade 4 · Communication through time",
      "Grade 5 · Hunter-gatherers and herders in Southern Africa",
      "Grade 5 · The first farmers in Southern Africa",
      "Grade 5 · An ancient African society: Egypt",
      "Grade 5 · A heritage trail through the provinces of South Africa",
      "Grade 6 · An African kingdom long ago: Mapungubwe",
      "Grade 6 · Explorers from Europe find Southern Africa",
      "Grade 6 · Democracy and citizenship in South Africa",
      "Grade 6 · Medicine through time",
    ],
    assessmentGuide: "",
  },
  {
    phase: "INTERMEDIATE_PHASE",
    subject: "Natural Sciences and Technology",
    gradeMin: 4,
    gradeMax: 6,
    sourceName: "CAPS Natural Sciences and Technology Grades 4-6 (Intermediate Phase)",
    sequence: [
      // Grade 4
      "Grade 4 · Living and non-living things",
      "Grade 4 · Structures of plants and animals",
      "Grade 4 · What plants need to grow",
      "Grade 4 · Habitats of animals",
      "Grade 4 · Structures for animal shelters",
      "Grade 4 · Materials around us",
      "Grade 4 · Solid materials",
      "Grade 4 · Strengthening materials",
      "Grade 4 · Strong frame structures",
      "Grade 4 · Energy and energy transfer",
      "Grade 4 · Energy around us",
      "Grade 4 · Movement energy in a system",
      "Grade 4 · Energy and sound",
      "Grade 4 · Planet Earth, the Sun and the Moon",
      "Grade 4 · Rocket systems",
      // Grade 5
      "Grade 5 · Plants and animals on Earth",
      "Grade 5 · Animal skeletons",
      "Grade 5 · Food chains",
      "Grade 5 · Life cycles",
      "Grade 5 · Skeletons as structures",
      "Grade 5 · Metals and non-metals",
      "Grade 5 · Uses of metals",
      "Grade 5 · Processing materials",
      "Grade 5 · Processed materials",
      "Grade 5 · Stored energy in fuels",
      "Grade 5 · Energy and electricity",
      "Grade 5 · Energy and movement",
      "Grade 5 · Systems for moving things",
      "Grade 5 · Planet Earth and its surface",
      "Grade 5 · Sedimentary rocks and fossils",
      // Grade 6
      "Grade 6 · Photosynthesis",
      "Grade 6 · Nutrients in food and nutrition",
      "Grade 6 · Ecosystems and food webs",
      "Grade 6 · Food processing",
      "Grade 6 · Solids, liquids and gases",
      "Grade 6 · Mixtures and solutions",
      "Grade 6 · Dissolving, water resources and purifying water",
      "Grade 6 · Electric circuits",
      "Grade 6 · Electrical conductors and insulators",
      "Grade 6 · Mains electricity",
      "Grade 6 · Systems to solve problems",
      "Grade 6 · The Solar System and movements of Earth and planets",
      "Grade 6 · The movement of the Moon",
      "Grade 6 · Systems for looking into space",
      "Grade 6 · Systems to explore the Moon and Mars",
    ],
    assessmentGuide: "",
  },
  {
    phase: "INTERMEDIATE_PHASE",
    subject: "IsiZulu Home Language",
    gradeMin: 4,
    gradeMax: 6,
    sourceName: "CAPS IsiZulu Home Language (IsiZulu Ulwimi Lwasekhaya) Grades 4-6 (Intermediate Phase)",
    sequence: [
      // Language is organised by the four skills rather than topics; this is
      // the ordered teaching sequence built from the CAPS skill strands and
      // the annual writing genre progression per grade.
      "Ukulalela nokukhuluma (Listening and speaking)",
      "Ukulalela ngokuqondisisa nokuphendula (Attentive listening and responding)",
      "Ukufunda (Reading)",
      "Ukufunda ngokuqondisisa okuqukethwe (Reading comprehension)",
      "Amagama, ukubhala amagama nespelingi (Word work, spelling and vocabulary)",
      "Ukubhala umusho nesigaba (Writing sentences and paragraphs)",
      "Umbhalo wochazayo nolandisayo (Descriptive and narrative writing)",
      "Imibhalo yokushintshisana: izaziso, izikhangiso, amaposta (Transactional texts: notices, adverts, posters)",
      "Imibhalo enomthetho: izincwadi, imibiko, amakhadi ezibingelelo (Formal texts: letters, reports, cards)",
      "Indaba emfishane nenganekwane (Short stories and folktales)",
      "Izinkondlo (Poetry)",
      "Inoveli nomdlalo/idrama (Novel and drama)",
      "Isakhiwo nokusetshenziswa kolimi: amabizo, izichasiso, izenzo (Language structure: nouns, modifiers, verbs)",
      "Izimpawu zokuloba nenkulumongqo (Punctuation and direct/reported speech)",
      "Inqubo yokubhala ephelele (The full writing process)",
    ],
    assessmentGuide: "",
  },
  // ---- STADIO: special grade with modules instead of subjects ----
  // Grade 13 = Stadio. Assessment guidelines are uploaded per module and land
  // in assessmentGuide; Slate feeds them to Gemini marking for these classes.
  {
    phase: "STADIO",
    subject: "Human Resource Management IV (HRM400)",
    gradeMin: STADIO_GRADE,
    gradeMax: STADIO_GRADE,
    sourceName: "Stadio — Human Resource Management IV (HRM400)",
    sequence: [
      "Module introduction and outcomes",
      "Human resource planning and talent acquisition",
      "Performance management and development",
      "Compensation and benefits strategy",
      "Employee and industrial relations",
      "HR analytics and decision making",
      "Ethics, legislation and governance in HRM",
      "Integrated HR case study and assessment preparation",
    ],
    assessmentGuide: "",
  },
  {
    phase: "STADIO",
    subject: "Human Resource Development IV (HRD400)",
    gradeMin: STADIO_GRADE,
    gradeMax: STADIO_GRADE,
    sourceName: "Stadio — Human Resource Development IV (HRD400)",
    sequence: [
      "Module introduction and outcomes",
      "Adult learning principles and training design",
      "Needs analysis and skills development planning",
      "Workplace learning programmes and facilitation",
      "Skills development legislation and B-BBEE",
      "Evaluating training impact and ROI",
      "Talent development and succession planning",
      "Integrated HRD case study and assessment preparation",
    ],
    assessmentGuide: "",
  },
  {
    phase: "STADIO",
    subject: "Organisational Behaviour IV (OBR400)",
    gradeMin: STADIO_GRADE,
    gradeMax: STADIO_GRADE,
    sourceName: "Stadio — Organisational Behaviour IV (OBR400)",
    sequence: [
      "Module introduction and outcomes",
      "Individual behaviour, personality and perception",
      "Motivation theory and practice",
      "Group dynamics and team effectiveness",
      "Leadership and power in organisations",
      "Organisational culture and change management",
      "Conflict, negotiation and decision making",
      "Integrated OB case study and assessment preparation",
    ],
    assessmentGuide: "",
  },
];

// Convenience: every subject that currently has a hardwired preset.
// Preset sequences that span several grades prefix each topic with its grade
// ("Grade 2 · ...", "Graad 2 · ...", "Kereite ya 2 · ..."). A class only teaches
// its own grade, so the sequence is narrowed before it is copied onto a class.
const GRADE_PREFIX = /^(?:Grade|Graad|Kereite ya|IBanga)\s+(R|\d+)\s+·/;

export function presetSequenceForGrade(preset: PresetEntry, grade: number): string[] {
  if (preset.gradeMin === preset.gradeMax) return preset.sequence;
  const token = grade === GRADE_R ? "R" : String(grade);
  const scoped = preset.sequence.filter((topic) => GRADE_PREFIX.exec(topic)?.[1] === token);
  // Some documents (e.g. IsiZulu HL) organise the phase by skill rather than by
  // grade; those sequences carry no prefix and are used whole.
  return scoped.length ? scoped : preset.sequence;
}

export function presetSubjects() {
  return Array.from(new Set(PRESET_CURRICULA.map((entry) => entry.subject)));
}

// Subjects a given grade may open a class for; a subject can appear in several
// phases (e.g. Mathematics in the Foundation and Intermediate Phase).
export function presetSubjectsForGrade(grade: number) {
  return PRESET_CURRICULA.filter((entry) => grade >= entry.gradeMin && grade <= entry.gradeMax).map((entry) => entry.subject);
}

export function presetForSubject(subject: string, grade: number): PresetEntry | null {
  return PRESET_CURRICULA.find((entry) => entry.subject === subject && grade >= entry.gradeMin && grade <= entry.gradeMax) ?? null;
}

// Upserts the registry into the catalog table (idempotent — used by the
// schema bootstrap and useful when the registry gains entries).
export async function syncPresetCurricula() {
  for (const entry of PRESET_CURRICULA) {
    await db
      .insert(presetCurriculaTable)
      .values({
        phase: entry.phase,
        subject: entry.subject,
        gradeMin: entry.gradeMin,
        gradeMax: entry.gradeMax,
        sourceName: entry.sourceName,
        sequence: entry.sequence,
        assessmentGuide: entry.assessmentGuide || null,
      })
      .onConflictDoUpdate({
        target: [presetCurriculaTable.phase, presetCurriculaTable.subject, presetCurriculaTable.gradeMin, presetCurriculaTable.gradeMax],
        set: {
          sequence: entry.sequence,
          sourceName: entry.sourceName,
          // Only overwrite the guide from the registry when a non-empty one is
          // hardwired; uploaded guides (until a set endpoint ships) are kept.
          ...(entry.assessmentGuide ? { assessmentGuide: entry.assessmentGuide } : {}),
        },
      });
  }
}

// Gate: a class can only be created against a preset subject at a covered
// grade. Returns the preset on success, or null when the subject is locked.
export async function resolvePresetForClass(subject: string, grade: number) {
  const preset = presetForSubject(subject, grade);
  if (!preset) return null;
  const [row] = await db
    .select()
    .from(presetCurriculaTable)
    .where(
      and(
        eq(presetCurriculaTable.subject, preset.subject),
        eq(presetCurriculaTable.gradeMin, preset.gradeMin),
        eq(presetCurriculaTable.gradeMax, preset.gradeMax),
      ),
    )
    .limit(1);
  return { preset, row: row ?? null };
}

export async function listPresetCurricula() {
  const rows = await db
    .select()
    .from(presetCurriculaTable)
    .orderBy(sql`${presetCurriculaTable.gradeMin}, ${presetCurriculaTable.subject}`);
  return rows.map((row) => ({
    id: row.id,
    phase: row.phase,
    subject: row.subject,
    gradeMin: row.gradeMin,
    gradeMax: row.gradeMax,
    sourceName: row.sourceName,
    sequence: row.sequence,
    hasAssessmentGuide: Boolean(row.assessmentGuide),
  }));
}
